FROM ubuntu:22.04
LABEL \
    org.opencontainers.image.title="OpenWrt v24.10.0 SDK" \
    org.opencontainers.image.vendor="Ubuntu22 build system" \
    org.opencontainers.image.licenses="Apache" \
    org.opencontainers.image.created="2025-04-09" \
    maintainer="slackman.cn"

ENV DEBIAN_FRONTEND=noninteractive \
    FORCE_UNSAFE_CONFIGURE=1 \
    TZ=Asia/Shanghai \
    SDK=openwrt-sdk-24.10.0-x86-64_gcc-13.3.0_musl.Linux-x86_64
    
RUN apt-get update && apt-get install -y --no-install-recommends tzdata \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime  \
    && echo $TZ > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata 

# Install build base (ext: zstd)
RUN apt-get update && apt-get install -y \
    build-essential clang flex bison g++ gawk \
    gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
    python3-distutils python3-setuptools rsync swig unzip zlib1g-dev file wget zstd \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


ARG CHECKSUM=94f55f15599b57e3b341681d6deffa8e6ce38fc829e0ed14ad5c4f4a4d85a4dc 

WORKDIR /openwrt
ADD --checksum=sha256:${CHECKSUM} https://downloads.openwrt.org/releases/24.10.0/targets/x86/64/${SDK}.tar.zst .
ADD --keep-git-dir https://github.com/mwarning/openwrt-examples.git openwrt-examples

RUN tar -xf ${SDK}.tar.zst && cd ${SDK} \
    && ./scripts/feeds update -a \
    && ./scripts/feeds install -a \
    && make defconfig


CMD ["/bin/bash"]